### ISSUE TITLE
[JOSS review] Missing data file from subject_example_data

### ISSUE THREAD

**Issue by ZeitgeberH** [elliohow/fMRI_ROI_Analysis_Tool#35]
Hi,
I was able to run fRAT under WSL2 in Windows 10 with functioning FSL.
As I go through the `Checking installation` step in the documentation,  it run into the `FileNotFoundError` error:  
_FileNotFoundError: No such file or directory '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_outliers.txt' for output 'out_file' of a MotionOutliers interface_

### Terminal output is as follows:

(frat) mlk@MingPC:~$ fRAT
fRAT 1.1.0 is developed and tested with Python 3.10.0.

INFO: Python version 3.10.9 is untested. Consider changing to version 3.10.0 if there are errors running fRAT.
----------------------------
----- Running fRAT_GUI -----
----------------------------
----- Running tests -----
----- Saved config file: fRAT_config.toml -----

fRAT 1.1.0 is developed and tested with Python 3.10.0.

INFO: Python version 3.10.9 is untested. Consider changing to version 3.10.0 if there are errors running fRAT.

--------------------------------
--- Statistical map creation ---
--------------------------------

Creating Temporal SNR maps.

Found 3 participant folders.

Starting processing pool using 24 cores.

Searching in folder: func
Saving output in directory: statmaps/test_maps

Creating statistical maps for participant: sub-02
      Creating statmaps for 16 files
        Analysing file: P14_MB2_S2.5_match_BW
        Analysing file: P1_MB3_S2_matchBW
        Analysing file: P7_MB2_S2_matchBW
        Analysing file: P13_MB1_S2.5_match_BW
        Analysing file: P3_MB3_S1.5
        Analysing file: P11_MB3_S1_match_BW
        Analysing file: P4_MB4_S1.5
        Analysing file: P2_MB1_S2_match_BW
        Analysing file: P16_MB4_S2.5_match_BW
        Analysing file: P9_MB1_S1_match_BW
        Analysing file: P15_MB3_S2.5_match_BW
        Analysing file: P5_MB4_S2_matchBW
        Analysing file: P8_MB1_S1.5_match_BW
        Analysing file: P6_MB2_S1.5
        Analysing file: P10_MB2_S1_match_BW
        Analysing file: P12_MB4_S1_match_BW
230310-11:54:12,852 nipype.interface INFO:
         stderr 2023-03-10T11:54:12.851991:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:12,954 nipype.interface INFO:
         stderr 2023-03-10T11:54:12.954617:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,163 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.162933:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,326 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.325954:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,368 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.367933:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,368 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.367949:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,371 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.371622:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,391 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.391104:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,468 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.468497:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,549 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.549016:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,550 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.550601:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,581 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.581737:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,593 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.593273:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,593 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.593283:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,593 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.593288:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-11:54:13,594 nipype.interface INFO:
         stderr 2023-03-10T11:54:13.594474:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
Exception in Tkinter callback
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_file' trait of a MotionOutliersOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_outliers.txt' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 248, in process_files_for_statmaps
    file, noise_file, redundant_files, outliers = prepare_statmap_files(file, no_ext_file, output_folder, participant)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 190, in prepare_statmap_files
    file, outlier_timepoints, outlier_files = remove_motion_outliers(file, no_ext_file, output_folder, participant)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 217, in remove_motion_outliers
    out_metric_values=outlier_values).run()
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_outliers.txt' for output 'out_file' of a MotionOutliers interface
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mlk/anaconda3/envs/frat/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/__main__.py", line 392, in <lambda>
    self.__setattr__(name, ttk.Button(self.settings_frame, command=lambda: func(self)))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/__main__.py", line 845, in run_tests
    statmap_calc('Temporal SNR', __version__, 'test_config.toml', path_to_example_data)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 396, in main
    calculate_statistical_maps(participants, output_folder, file_location, func)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 281, in calculate_statistical_maps
    outliers = list(pool.starmap(process_files_for_statmaps, iterable))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 774, in get
    raise self._value
FileNotFoundError: No such file or directory '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_outliers.txt' for output 'out_file' of a MotionOutliers interface
`

**Comment by elliohow** [comment]
Does the same error occur if you use python 3.10 to run fRAT?

**Comment by ZeitgeberH** [comment]
Yeah. So error under Python 3.10. See below.
Is a FLS version mismatch?  the FSL i installed seems to be 6.0
```
flirt -version
FLIRT version 6.0
```

fRAT 1.1.0 is developed and tested with Python 3.10.0.

----------------------------
----- Running fRAT_GUI -----
----------------------------
----- Running tests -----
----- Saved config file: fRAT_config.toml -----

fRAT 1.1.0 is developed and tested with Python 3.10.0.


--------------------------------
--- Statistical map creation ---
--------------------------------

Creating Temporal SNR maps.

Found 3 participant folders.

Starting processing pool using 24 cores.

Searching in folder: func
Saving output in directory: statmaps/test_maps

Creating statistical maps for participant: sub-02
      Creating statmaps for 16 files
        Analysing file: P14_MB2_S2.5_match_BW
        Analysing file: P1_MB3_S2_matchBW
        Analysing file: P7_MB2_S2_matchBW
        Analysing file: P13_MB1_S2.5_match_BW
        Analysing file: P3_MB3_S1.5
        Analysing file: P11_MB3_S1_match_BW
        Analysing file: P4_MB4_S1.5
        Analysing file: P2_MB1_S2_match_BW
        Analysing file: P16_MB4_S2.5_match_BW
        Analysing file: P9_MB1_S1_match_BW
        Analysing file: P15_MB3_S2.5_match_BW
        Analysing file: P5_MB4_S2_matchBW
        Analysing file: P8_MB1_S1.5_match_BW
        Analysing file: P6_MB2_S1.5
        Analysing file: P10_MB2_S1_match_BW
        Analysing file: P12_MB4_S1_match_BW
230310-12:58:29,733 nipype.interface INFO:
         stderr 2023-03-10T12:58:29.733692:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:29,733 nipype.interface INFO:
         stderr 2023-03-10T12:58:29.733647:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:29,735 nipype.interface INFO:
         stderr 2023-03-10T12:58:29.735171:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:29,908 nipype.interface INFO:
         stderr 2023-03-10T12:58:29.907811:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:29,908 nipype.interface INFO:
         stderr 2023-03-10T12:58:29.907877:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:29,908 nipype.interface INFO:
         stderr 2023-03-10T12:58:29.907883:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:29,908 nipype.interface INFO:
         stderr 2023-03-10T12:58:29.907851:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:29,908 nipype.interface INFO:
         stderr 2023-03-10T12:58:29.907822:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:30,154 nipype.interface INFO:
         stderr 2023-03-10T12:58:30.154009:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:30,154 nipype.interface INFO:
         stderr 2023-03-10T12:58:30.154009:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:30,154 nipype.interface INFO:
         stderr 2023-03-10T12:58:30.154017:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:30,154 nipype.interface INFO:
         stderr 2023-03-10T12:58:30.154009:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:30,155 nipype.interface INFO:
         stderr 2023-03-10T12:58:30.154631:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:30,155 nipype.interface INFO:
         stderr 2023-03-10T12:58:30.155338:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:30,256 nipype.interface INFO:
         stderr 2023-03-10T12:58:30.256185:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230310-12:58:30,366 nipype.interface INFO:
         stderr 2023-03-10T12:58:30.366462:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
Exception in Tkinter callback
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_metric_plot' trait of a MotionOutliersOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_metrics.png' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 248, in process_files_for_statmaps
    file, noise_file, redundant_files, outliers = prepare_statmap_files(file, no_ext_file, output_folder, participant)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 190, in prepare_statmap_files
    file, outlier_timepoints, outlier_files = remove_motion_outliers(file, no_ext_file, output_folder, participant)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 217, in remove_motion_outliers
    out_metric_values=outlier_values).run()
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_metrics.png' for output 'out_metric_plot' of a MotionOutliers interface
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mlk/anaconda3/envs/frat310/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/__main__.py", line 392, in <lambda>
    self.__setattr__(name, ttk.Button(self.settings_frame, command=lambda: func(self)))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/__main__.py", line 845, in run_tests
    statmap_calc('Temporal SNR', __version__, 'test_config.toml', path_to_example_data)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 396, in main
    calculate_statistical_maps(participants, output_folder, file_location, func)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 281, in calculate_statistical_maps
    outliers = list(pool.starmap(process_files_for_statmaps, iterable))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 774, in get
    raise self._value
FileNotFoundError: No such file or directory '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_metrics.png' for output 'out_metric_plot' of a MotionOutliers interface

**Comment by elliohow** [comment]
Have any files been saved in the test_maps folder for subject sub-02?

**Comment by ZeitgeberH** [comment]
Yeah. A few.  But no `motion_corrected` ,  `tMean`,  `tSNR`,` tStd` files

> ls ~/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/ -ls
total 2388
164 -rw-r--r-- 1 mlk mlk 166547 Mar 10 12:58 P10_MB2_S1_match_BW_noise_volume.nii.gz
144 -rw-r--r-- 1 mlk mlk 143972 Mar 10 12:58 P11_MB3_S1_match_BW_noise_volume.nii.gz
144 -rw-r--r-- 1 mlk mlk 146581 Mar 10 12:58 P12_MB4_S1_match_BW_noise_volume.nii.gz
132 -rw-r--r-- 1 mlk mlk 133359 Mar 10 12:58 P13_MB1_S2.5_match_BW_noise_volume.nii.gz
172 -rw-r--r-- 1 mlk mlk 172303 Mar 10 12:58 P14_MB2_S2.5_match_BW_noise_volume.nii.gz
168 -rw-r--r-- 1 mlk mlk 169695 Mar 10 12:58 P15_MB3_S2.5_match_BW_noise_volume.nii.gz
180 -rw-r--r-- 1 mlk mlk 182529 Mar 10 12:58 P16_MB4_S2.5_match_BW_noise_volume.nii.gz
164 -rw-r--r-- 1 mlk mlk 165655 Mar 10 12:58 P1_MB3_S2_matchBW_noise_volume.nii.gz
128 -rw-r--r-- 1 mlk mlk 127140 Mar 10 12:58 P2_MB1_S2_match_BW_noise_volume.nii.gz
156 -rw-r--r-- 1 mlk mlk 157602 Mar 10 12:58 P3_MB3_S1.5_noise_volume.nii.gz
148 -rw-r--r-- 1 mlk mlk 148810 Mar 10 12:58 P4_MB4_S1.5_noise_volume.nii.gz
160 -rw-r--r-- 1 mlk mlk 162152 Mar 10 12:58 P5_MB4_S2_matchBW_noise_volume.nii.gz
128 -rw-r--r-- 1 mlk mlk 129834 Mar 10 12:58 P6_MB2_S1.5_noise_volume.nii.gz
168 -rw-r--r-- 1 mlk mlk 168002 Mar 10 12:58 P7_MB2_S2_matchBW_noise_volume.nii.gz
128 -rw-r--r-- 1 mlk mlk 128268 Mar 10 12:58 P8_MB1_S1.5_match_BW_noise_volume.nii.gz
 96 -rw-r--r-- 1 mlk mlk  94950 Mar 10 12:58 P9_MB1_S1_match_BW_noise_volume.nii.gz
  8 -rw-r--r-- 1 mlk mlk   4275 Mar 10 12:58 statmap_config.toml

**Comment by elliohow** [comment]
I've updated the example data files (https://osf.io/pbm3d/), the [installation instructions](https://fmri-roi-analysis-tool.readthedocs.io/en/latest/installation.html#on-linux-and-wsl2) for linux and WSL2, and made some changes that might fix this issue. Are you able to try the latest version following the new instructions to see if this fixes the issue?

**Comment by ZeitgeberH** [comment]
Hi @elliohow 
I re-downloaded the data and updated fRAT to new version. It looks like the problem persist.
See below.
I'll try this on a Linux system this weekend, and report back what I found.


$ fRAT

fRAT 1.1.2 is developed and tested with Python 3.10.

----------------------------
----- Running fRAT_GUI -----
----------------------------
----- Running tests -----
----- Saved config file: fRAT_config.toml -----

fRAT 1.1.2 is developed and tested with Python 3.10.


--------------------------------
--- Statistical map creation ---
--------------------------------

Creating Temporal SNR maps.

Found 3 participant folders.

Starting processing pool using 24 cores.

Searching in folder: func
Saving output in directory: statmaps/test_maps

Creating statistical maps for participant: sub-02
      Creating statmaps for 16 files
        Analysing file: P14_MB2_S2.5_match_BW
        Analysing file: P1_MB3_S2_matchBW
        Analysing file: P7_MB2_S2_matchBW
        Analysing file: P13_MB1_S2.5_match_BW
        Analysing file: P3_MB3_S1.5
        Analysing file: P11_MB3_S1_match_BW
        Analysing file: P4_MB4_S1.5
        Analysing file: P2_MB1_S2_match_BW
        Analysing file: P16_MB4_S2.5_match_BW
        Analysing file: P9_MB1_S1_match_BW
        Analysing file: P15_MB3_S2.5_match_BW
        Analysing file: P5_MB4_S2_matchBW
        Analysing file: P8_MB1_S1.5_match_BW
        Analysing file: P6_MB2_S1.5
        Analysing file: P10_MB2_S1_match_BW
        Analysing file: P12_MB4_S1_match_BW
230316-14:15:03,487 nipype.interface INFO:
         stderr 2023-03-16T14:15:03.487089:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:03,690 nipype.interface INFO:
         stderr 2023-03-16T14:15:03.690732:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:03,772 nipype.interface INFO:
         stderr 2023-03-16T14:15:03.772377:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:03,851 nipype.interface INFO:
         stderr 2023-03-16T14:15:03.851643:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:03,851 nipype.interface INFO:
         stderr 2023-03-16T14:15:03.851672:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:03,851 nipype.interface INFO:
         stderr 2023-03-16T14:15:03.851677:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:03,987 nipype.interface INFO:
         stderr 2023-03-16T14:15:03.986986:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:04,6 nipype.interface INFO:
         stderr 2023-03-16T14:15:04.005910:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:04,7 nipype.interface INFO:
         stderr 2023-03-16T14:15:04.007771:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:04,101 nipype.interface INFO:
         stderr 2023-03-16T14:15:04.100986:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:04,114 nipype.interface INFO:
         stderr 2023-03-16T14:15:04.114405:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:04,176 nipype.interface INFO:
         stderr 2023-03-16T14:15:04.175970:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:04,176 nipype.interface INFO:
         stderr 2023-03-16T14:15:04.175970:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:04,176 nipype.interface INFO:
         stderr 2023-03-16T14:15:04.175996:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:04,177 nipype.interface INFO:
         stderr 2023-03-16T14:15:04.177502:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
230316-14:15:04,294 nipype.interface INFO:
         stderr 2023-03-16T14:15:04.294509:/home/mlk/fsl/bin/fsl_motion_outliers: 1: bc: not found
Exception in Tkinter callback
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_file' trait of a MotionOutliersOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_outliers.txt' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 253, in process_files_for_statmaps
    file, noise_file, redundant_files, outliers = prepare_statmap_files(file, no_ext_file, output_folder, participant)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 190, in prepare_statmap_files
    file, outlier_timepoints, outlier_files = remove_motion_outliers(file, no_ext_file, output_folder, participant)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 222, in remove_motion_outliers
    out_metric_values=outlier_values).run()
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_outliers.txt' for output 'out_file' of a MotionOutliers interface
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mlk/anaconda3/envs/frat310/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/__main__.py", line 384, in <lambda>
    self.__setattr__(name, ttk.Button(self.settings_frame, command=lambda: func(self)))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/__main__.py", line 837, in run_tests
    statmap_calc('Temporal SNR', __version__, 'test_config.toml', path_to_example_data_input)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 401, in main
    calculate_statistical_maps(participants, output_folder, file_location, func)
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/fRAT/utils/statmap.py", line 286, in calculate_statistical_maps
    outliers = list(pool.starmap(process_files_for_statmaps, iterable))
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/mlk/.local/pipx/venvs/frat-brain/lib/python3.10/site-packages/multiprocess/pool.py", line 774, in get
    raise self._value
FileNotFoundError: No such file or directory '/home/mlk/Documents/fRAT/subject_example_data/sub-02/statmaps/test_maps/P13_MB1_S2.5_match_BW_outliers.txt' for output 'out_file' of a MotionOutliers interface

**Comment by elliohow** [comment]
I can't replicate this issue. Although as it can create the files that don't require FSL, but it can't create any files that do, it might be an FSL setup issue.

**Comment by billbrod** [comment]
I was able to get the test to run using Linux (Fedora 36), FSL version 6.0, python 3.10, fRAT 1.1.3.

**Comment by elliohow** [comment]
I was able to run the test using Ubuntu 18.04 both natively and with WSL (FSL version 6.0, python 3.10, fRAT 1.2.0).

**Comment by elliohow** [comment]
Thank you for the solution. I've added it to the installation page.
